version: '3.8'

services:
  miniprograms:
    image: registry.cn-shenzhen.aliyuncs.com/muxi/miniprograms:v1.0.0
    ports:
      - "8082:8080"
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./db:/app/db
